package leetCode;

/*
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * https://leetcode.com/problems/find-the-difference/
 */
public class FindTheDifference {
	
	public char findTheDifference(String s, String t) {
		char[] charCount = new char[26];
		
		// populate with string t
		for (int i = 0; i < t.length(); i++) {
			charCount[t.charAt(i) - 'a']++;
		}
		
		// depop with string s
		for (int i = 0; i < s.length(); i++) {
			charCount[s.charAt(i) - 'a']--;
		}
		
		// find first non zero
		for (int i = 0; i < 26; i++) {
			if (charCount[i] != 0)
				return (char) ((char) i + 'a');
		}
		
		return 0; // something wrong
    }

}
